environment:
  global:
    SHELLOPTS: igncr
    CYG_BASH: C:\Cygwin\bin\bash

matrix:
  fast_finish: true

install:
  - env
  - SET PATH="C:\Cygwin\bin";%PATH%
  - env

build: false

test_script:
  - '%CYGBASH% tests\test_multibuild.sh' 
